import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || (window.location.hostname === 'localhost' ? 'http://localhost:4000/api' : '/api');
const labels = { TICKET: 'INBOX', CLASSIFIER: 'CLASSIFIER', TOOLS: 'TOOLS / APIs', EVIDENCE: 'EVIDENCE', ORCHESTRATOR: 'ORCHESTRATOR', RAG: 'POLICY RAG', SAFETY_GATE: 'SAFETY GATE', RESOLUTION: 'RESOLUTION' };
function App() {
  const [data, setData] = useState({ tickets: [], runs: [], escalations: [], audit: [], metrics: {} });
  const [run, setRun] = useState(null); const [selected, setSelected] = useState('demo1'); const [loading, setLoading] = useState(false); const [view, setView] = useState('Dashboard');
  const refresh = () => fetch(`${API}/dashboard`).then((r) => r.json()).then(setData).catch(() => {});
  useEffect(() => { refresh(); }, []);
  async function executeDemo() { setLoading(true); setRun(null); const response = await fetch(`${API}/resolve/demo`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ demo: selected }) }); const next = await response.json(); setRun({ ...next, shown: 0 }); for (let i = 1; i <= next.events.length; i++) { await new Promise((x) => setTimeout(x, 400)); setRun((old) => ({ ...old, shown: i })); } setLoading(false); refresh(); }
  async function act(id, action) { await fetch(`${API}/escalations/${id}/${action}`, { method: 'POST' }); refresh(); setRun((x) => x && ({ ...x, escalationHandled: action })); }
  const events = run ? run.events.slice(0, run.shown || 0) : [];
  const activeTicket = selected === 'demo1' ? data.tickets.find((t) => t.id === 'TKT-1001') : data.tickets.find((t) => t.id === 'TKT-2001');
  return <div className="shell"><aside><div className="brand"><span>R</span><div>RESOLVEIQ<small>TEAM NEXORA</small></div></div><p className="tagline">Autonomous where it’s safe.<br/>Human where it matters.</p><nav>{['Dashboard','Tickets','Live Resolution','Escalations','Policies','Audit Logs'].map((x) => <button className={view === x ? 'active' : ''} onClick={() => setView(x)} key={x}>{x}<i>{x === 'Escalations' && data.escalations.filter((e) => e.status === 'PENDING').length || ''}</i></button>)}</nav><div className="guard"><b>SAFETY GATE</b><span>ACTIVE / POLICY-BOUND</span></div></aside><main><header><div><p className="eyebrow">{view.toUpperCase()} / OPERATIONS CONSOLE</p><h1>{view === 'Dashboard' ? 'Resolution control room' : view}</h1></div><div className="live"><em></em> SYSTEMS NOMINAL</div></header>
  {view === 'Dashboard' || view === 'Live Resolution' ? <><section className="hero"><div><p className="eyebrow">AUTONOMOUS RESOLUTION ENGINE</p><h2>AI knows when<br/><strong>not to act.</strong></h2><p>ResolveIQ investigates across systems, validates policy and evidence, then either acts or hands a complete case to a human.</p><div className="workflow"><span>CUSTOMER<br/>TICKET</span><b>↓</b><span>CLASSIFIER</span><b>↓</b><span>ORCHESTRATOR</span><b>↓</b><span>TOOLS</span><b>↓</b><span>EVIDENCE</span><b>↓</b><span className="red">SAFETY GATE</span><b>↙ ↘</b><span>ACT / HUMAN</span></div></div><div className="demo"><p className="eyebrow">RUN DEMO</p><button onClick={() => setSelected('demo1')} className={selected === 'demo1' ? 'choice selected' : 'choice'}><b>01</b><span>DELIVERED BUT<br/>NOT RECEIVED</span></button><button onClick={() => setSelected('demo2')} className={selected === 'demo2' ? 'choice selected' : 'choice'}><b>02</b><span>CANCEL ₹80,000<br/>ORDER</span></button><button className="run" onClick={executeDemo} disabled={loading}>{loading ? 'RESOLVING…' : 'RUN RESOLUTION →'}</button><small>Deterministic demo pipeline. No external LLM required.</small></div></section>
  <Metrics metrics={data.metrics}/><section className="resolution"><div className="sectionhead"><div><p className="eyebrow">LIVE INVESTIGATION</p><h3>{activeTicket?.subject || 'Select a demo case'}</h3></div>{run && <Decision decision={run.decision}/>}</div><div className="resolutiongrid"><article className="ticket"><p className="mono">{activeTicket?.id} · {activeTicket?.customerId}</p><h4>Customer issue</h4><blockquote>“{activeTicket?.message}”</blockquote><div className="status">{activeTicket?.status || 'OPEN'}</div><h4>Required systems</h4><div className="chips">{(run?.classification?.requiredSystems || ['order','shipping','inventory','policy']).map((x) => <span key={x}>{x}</span>)}</div></article><article className="timeline">{events.length ? events.map((e, i) => <div className={'event ' + e.stage.toLowerCase()} key={e.id}><time>{new Date(e.timestamp).toLocaleTimeString([], { hour:'2-digit', minute:'2-digit', second:'2-digit' })}</time><div className="dot"></div><div><b>{labels[e.stage]}</b><p>{e.message}</p>{e.status === 'WARNING' && <small className="warning">EVIDENCE CONFLICT DETECTED → STRATEGY UPDATED</small>}</div></div>) : <div className="empty">Select a case and run its live resolution pipeline.</div>}</article><article className="evidence"><p className="eyebrow">EVIDENCE + DECISION</p>{run ? <>{run.evidence.map((e) => <div className="evidenceRow" key={e.type}><b>✓</b><span>{e.type.replaceAll('_', ' ')}</span><small>{e.source}</small></div>)}<h4>Policy retrieval</h4>{run.policies.map((p) => <div className="policy" key={p.id}><b>{p.name}</b><span>{p.section}</span><small>RELEVANCE {Math.round(p.retrievalScore * 100)}%</small></div>)}<p className="reason">{run.decision?.reason}</p>{run.escalationId && !run.escalationHandled && <div className="human"><b>HUMAN APPROVAL</b><p>Cancellation remains blocked.</p><button onClick={() => act(run.escalationId, 'approve')}>APPROVE</button><button onClick={() => act(run.escalationId, 'reject')}>REJECT</button></div>}</> : <div className="empty">Evidence will be assembled from live tool calls.</div>}</article></div></section></> : <Secondary view={view} data={data} onApprove={(id) => act(id, 'approve')} onReject={(id) => act(id, 'reject')}/>}</main></div>;
}
function Metrics({ metrics }) { return <section className="metrics">{[['ACTIVE TICKETS',metrics.activeTickets],['AUTONOMOUS RESOLUTIONS',metrics.autonomousResolutions],['HUMAN ESCALATIONS',metrics.humanEscalations],['AVG RESOLUTION TIME',metrics.averageResolutionTime]].map(([x,y]) => <div key={x}><small>{x}</small><b>{y ?? '—'}</b></div>)}<span>Values reflect current seeded/demo data—not production benchmarks.</span></section> }
function Decision({ decision }) { if (!decision) return null; const auto = decision.decision === 'AUTO_EXECUTE'; return <div className={'decision ' + (auto ? 'safe' : 'humanDecision')}><b>{Math.round(decision.confidence * 100)}%</b><span>DEMO CONFIDENCE</span><strong>{auto ? '✓ RESOLVED AUTONOMOUSLY' : '→ HUMAN APPROVAL REQUIRED'}</strong></div> }
function Secondary({ view, data, onApprove, onReject }) { const items = view === 'Policies' ? (data.policies || []) : view === 'Audit Logs' ? data.audit : view === 'Escalations' ? data.escalations : data.tickets; return <section className="table"><p className="eyebrow">{view.toUpperCase()} / AUDITABLE RECORDS</p><h3>{view}</h3>{items.length ? items.map((x) => <div className="tableRow" key={x.id}><b>{x.id || x.action}</b><span>{x.subject || x.action || x.name || x.recommendation}</span><small>{x.status || x.section || x.timestamp}</small>{view === 'Escalations' && x.status === 'PENDING' && <div><button onClick={() => onApprove(x.id)}>APPROVE</button><button onClick={() => onReject(x.id)}>REJECT</button></div>}</div>) : <div className="empty">No records yet. Run a demo to generate operational history.</div>}</section> }
createRoot(document.getElementById('root')).render(<App/>);
